<?php

$country_codes = array(
  array('A' => '+7 840','B' => 'Abkhazia'),
  array('A' => '+93','B' => 'Afghanistan'),
  array('A' => '+355','B' => 'Albania'),
  array('A' => '+213','B' => 'Algeria'),
  array('A' => '+1 684','B' => 'American Samoa'),
  array('A' => '+376','B' => 'Andorra'),
  array('A' => '+244','B' => 'Angola'),
  array('A' => '+1 264','B' => 'Anguilla'),
  array('A' => '+1 268','B' => 'Antigua and Barbuda'),
  array('A' => '+54','B' => 'Argentina'),
  array('A' => '+374','B' => 'Armenia'),
  array('A' => '+297','B' => 'Aruba'),
  array('A' => '+247','B' => 'Ascension'),
  array('A' => '+61','B' => 'Australia'),
  array('A' => '+672','B' => 'Australian External Territories'),
  array('A' => '+43','B' => 'Austria'),
  array('A' => '+994','B' => 'Azerbaijan'),
  array('A' => '+1 242','B' => 'Bahamas'),
  array('A' => '+973','B' => 'Bahrain'),
  array('A' => '+880','B' => 'Bangladesh'),
  array('A' => '+1 246','B' => 'Barbados'),
  array('A' => '+1 268','B' => 'Barbuda'),
  array('A' => '+375','B' => 'Belarus'),
  array('A' => '+32','B' => 'Belgium'),
  array('A' => '+501','B' => 'Belize'),
  array('A' => '+229','B' => 'Benin'),
  array('A' => '+1 441','B' => 'Bermuda'),
  array('A' => '+975','B' => 'Bhutan'),
  array('A' => '+591','B' => 'Bolivia'),
  array('A' => '+387','B' => 'Bosnia and Herzegovina'),
  array('A' => '+267','B' => 'Botswana'),
  array('A' => '+55','B' => 'Brazil'),
  array('A' => '+246','B' => 'British Indian Ocean Territory'),
  array('A' => '+1 284','B' => 'British Virgin Islands'),
  array('A' => '+673','B' => 'Brunei'),
  array('A' => '+359','B' => 'Bulgaria'),
  array('A' => '+226','B' => 'Burkina Faso'),
  array('A' => '+257','B' => 'Burundi'),
  array('A' => '+855','B' => 'Cambodia'),
  array('A' => '+237','B' => 'Cameroon'),
  array('A' => '+1','B' => 'Canada'),
  array('A' => '+238','B' => 'Cape Verde'),
  array('A' => '+ 345','B' => 'Cayman Islands'),
  array('A' => '+236','B' => 'Central African Republic'),
  array('A' => '+235','B' => 'Chad'),
  array('A' => '+56','B' => 'Chile'),
  array('A' => '+86','B' => 'China'),
  array('A' => '+61','B' => 'Christmas Island'),
  array('A' => '+61','B' => 'Cocos-Keeling Islands'),
  array('A' => '+57','B' => 'Colombia'),
  array('A' => '+269','B' => 'Comoros'),
  array('A' => '+242','B' => 'Congo'),
  array('A' => '+243','B' => 'Congo, Dem. Rep. of (Zaire)'),
  array('A' => '+682','B' => 'Cook Islands'),
  array('A' => '+506','B' => 'Costa Rica'),
  array('A' => '+385','B' => 'Croatia'),
  array('A' => '+53','B' => 'Cuba'),
  array('A' => '+599','B' => 'Curacao'),
  array('A' => '+537','B' => 'Cyprus'),
  array('A' => '+420','B' => 'Czech Republic'),
  array('A' => '+45','B' => 'Denmark'),
  array('A' => '+246','B' => 'Diego Garcia'),
  array('A' => '+253','B' => 'Djibouti'),
  array('A' => '+1 767','B' => 'Dominica'),
  array('A' => '+1 809','B' => 'Dominican Republic'),
  array('A' => '+670','B' => 'East Timor'),
  array('A' => '+56','B' => 'Easter Island'),
  array('A' => '+593','B' => 'Ecuador'),
  array('A' => '+20','B' => 'Egypt'),
  array('A' => '+503','B' => 'El Salvador'),
  array('A' => '+240','B' => 'Equatorial Guinea'),
  array('A' => '+291','B' => 'Eritrea'),
  array('A' => '+372','B' => 'Estonia'),
  array('A' => '+251','B' => 'Ethiopia'),
  array('A' => '+500','B' => 'Falkland Islands'),
  array('A' => '+298','B' => 'Faroe Islands'),
  array('A' => '+679','B' => 'Fiji'),
  array('A' => '+358','B' => 'Finland'),
  array('A' => '+33','B' => 'France'),
  array('A' => '+596','B' => 'French Antilles'),
  array('A' => '+594','B' => 'French Guiana'),
  array('A' => '+689','B' => 'French Polynesia'),
  array('A' => '+241','B' => 'Gabon'),
  array('A' => '+220','B' => 'Gambia'),
  array('A' => '+995','B' => 'Georgia'),
  array('A' => '+49','B' => 'Germany'),
  array('A' => '+233','B' => 'Ghana'),
  array('A' => '+350','B' => 'Gibraltar'),
  array('A' => '+30','B' => 'Greece'),
  array('A' => '+299','B' => 'Greenland'),
  array('A' => '+1 473','B' => 'Grenada'),
  array('A' => '+590','B' => 'Guadeloupe'),
  array('A' => '+1 671','B' => 'Guam'),
  array('A' => '+502','B' => 'Guatemala'),
  array('A' => '+224','B' => 'Guinea'),
  array('A' => '+245','B' => 'Guinea-Bissau'),
  array('A' => '+595','B' => 'Guyana'),
  array('A' => '+509','B' => 'Haiti'),
  array('A' => '+504','B' => 'Honduras'),
  array('A' => '+852','B' => 'Hong Kong SAR China'),
  array('A' => '+36','B' => 'Hungary'),
  array('A' => '+354','B' => 'Iceland'),
  array('A' => '+91','B' => 'India'),
  array('A' => '+62','B' => 'Indonesia'),
  array('A' => '+98','B' => 'Iran'),
  array('A' => '+964','B' => 'Iraq'),
  array('A' => '+353','B' => 'Ireland'),
  array('A' => '+972','B' => 'Israel'),
  array('A' => '+39','B' => 'Italy'),
  array('A' => '+225','B' => 'Ivory Coast'),
  array('A' => '+1 876','B' => 'Jamaica'),
  array('A' => '+81','B' => 'Japan'),
  array('A' => '+962','B' => 'Jordan'),
  array('A' => '+7 7','B' => 'Kazakhstan'),
  array('A' => '+254','B' => 'Kenya'),
  array('A' => '+686','B' => 'Kiribati'),
  array('A' => '+965','B' => 'Kuwait'),
  array('A' => '+996','B' => 'Kyrgyzstan'),
  array('A' => '+856','B' => 'Laos'),
  array('A' => '+371','B' => 'Latvia'),
  array('A' => '+961','B' => 'Lebanon'),
  array('A' => '+266','B' => 'Lesotho'),
  array('A' => '+231','B' => 'Liberia'),
  array('A' => '+218','B' => 'Libya'),
  array('A' => '+423','B' => 'Liechtenstein'),
  array('A' => '+370','B' => 'Lithuania'),
  array('A' => '+352','B' => 'Luxembourg'),
  array('A' => '+853','B' => 'Macau SAR China'),
  array('A' => '+389','B' => 'Macedonia'),
  array('A' => '+261','B' => 'Madagascar'),
  array('A' => '+265','B' => 'Malawi'),
  array('A' => '+60','B' => 'Malaysia'),
  array('A' => '+960','B' => 'Maldives'),
  array('A' => '+223','B' => 'Mali'),
  array('A' => '+356','B' => 'Malta'),
  array('A' => '+692','B' => 'Marshall Islands'),
  array('A' => '+596','B' => 'Martinique'),
  array('A' => '+222','B' => 'Mauritania'),
  array('A' => '+230','B' => 'Mauritius'),
  array('A' => '+262','B' => 'Mayotte'),
  array('A' => '+52','B' => 'Mexico'),
  array('A' => '+691','B' => 'Micronesia'),
  array('A' => '+1 808','B' => 'Midway Island'),
  array('A' => '+373','B' => 'Moldova'),
  array('A' => '+377','B' => 'Monaco'),
  array('A' => '+976','B' => 'Mongolia'),
  array('A' => '+382','B' => 'Montenegro'),
  array('A' => '+1664','B' => 'Montserrat'),
  array('A' => '+212','B' => 'Morocco'),
  array('A' => '+95','B' => 'Myanmar'),
  array('A' => '+264','B' => 'Namibia'),
  array('A' => '+674','B' => 'Nauru'),
  array('A' => '+977','B' => 'Nepal'),
  array('A' => '+31','B' => 'Netherlands'),
  array('A' => '+599','B' => 'Netherlands Antilles'),
  array('A' => '+1 869','B' => 'Nevis'),
  array('A' => '+687','B' => 'New Caledonia'),
  array('A' => '+64','B' => 'New Zealand'),
  array('A' => '+505','B' => 'Nicaragua'),
  array('A' => '+227','B' => 'Niger'),
  array('A' => '+234','B' => 'Nigeria'),
  array('A' => '+683','B' => 'Niue'),
  array('A' => '+672','B' => 'Norfolk Island'),
  array('A' => '+850','B' => 'North Korea'),
  array('A' => '+1 670','B' => 'Northern Mariana Islands'),
  array('A' => '+47','B' => 'Norway'),
  array('A' => '+968','B' => 'Oman'),
  array('A' => '+92','B' => 'Pakistan'),
  array('A' => '+680','B' => 'Palau'),
  array('A' => '+970','B' => 'Palestinian Territory'),
  array('A' => '+507','B' => 'Panama'),
  array('A' => '+675','B' => 'Papua New Guinea'),
  array('A' => '+595','B' => 'Paraguay'),
  array('A' => '+51','B' => 'Peru'),
  array('A' => '+63','B' => 'Philippines'),
  array('A' => '+48','B' => 'Poland'),
  array('A' => '+351','B' => 'Portugal'),
  array('A' => '+1 787','B' => 'Puerto Rico'),
  array('A' => '+974','B' => 'Qatar'),
  array('A' => '+262','B' => 'Reunion'),
  array('A' => '+40','B' => 'Romania'),
  array('A' => '+7','B' => 'Russia'),
  array('A' => '+250','B' => 'Rwanda'),
  array('A' => '+685','B' => 'Samoa'),
  array('A' => '+378','B' => 'San Marino'),
  array('A' => '+966','B' => 'Saudi Arabia'),
  array('A' => '+221','B' => 'Senegal'),
  array('A' => '+381','B' => 'Serbia'),
  array('A' => '+248','B' => 'Seychelles'),
  array('A' => '+232','B' => 'Sierra Leone'),
  array('A' => '+65','B' => 'Singapore'),
  array('A' => '+421','B' => 'Slovakia'),
  array('A' => '+386','B' => 'Slovenia'),
  array('A' => '+677','B' => 'Solomon Islands'),
  array('A' => '+27','B' => 'South Africa'),
  array('A' => '+500','B' => 'South Georgia and the South Sandwich Islands'),
  array('A' => '+82','B' => 'South Korea'),
  array('A' => '+34','B' => 'Spain'),
  array('A' => '+94','B' => 'Sri Lanka'),
  array('A' => '+249','B' => 'Sudan'),
  array('A' => '+597','B' => 'Suriname'),
  array('A' => '+268','B' => 'Swaziland'),
  array('A' => '+46','B' => 'Sweden'),
  array('A' => '+41','B' => 'Switzerland'),
  array('A' => '+963','B' => 'Syria'),
  array('A' => '+886','B' => 'Taiwan'),
  array('A' => '+992','B' => 'Tajikistan'),
  array('A' => '+255','B' => 'Tanzania'),
  array('A' => '+66','B' => 'Thailand'),
  array('A' => '+670','B' => 'Timor Leste'),
  array('A' => '+228','B' => 'Togo'),
  array('A' => '+690','B' => 'Tokelau'),
  array('A' => '+676','B' => 'Tonga'),
  array('A' => '+1 868','B' => 'Trinidad and Tobago'),
  array('A' => '+216','B' => 'Tunisia'),
  array('A' => '+90','B' => 'Turkey'),
  array('A' => '+993','B' => 'Turkmenistan'),
  array('A' => '+1 649','B' => 'Turks and Caicos Islands'),
  array('A' => '+688','B' => 'Tuvalu'),
  array('A' => '+1 340','B' => 'U.S. Virgin Islands'),
  array('A' => '+256','B' => 'Uganda'),
  array('A' => '+380','B' => 'Ukraine'),
  array('A' => '+971','B' => 'United Arab Emirates'),
  array('A' => '+44','B' => 'United Kingdom'),
  array('A' => '+1','B' => 'United States'),
  array('A' => '+598','B' => 'Uruguay'),
  array('A' => '+998','B' => 'Uzbekistan'),
  array('A' => '+678','B' => 'Vanuatu'),
  array('A' => '+58','B' => 'Venezuela'),
  array('A' => '+84','B' => 'Vietnam'),
  array('A' => '+1 808','B' => 'Wake Island'),
  array('A' => '+681','B' => 'Wallis and Futuna'),
  array('A' => '+967','B' => 'Yemen'),
  array('A' => '+260','B' => 'Zambia'),
  array('A' => '+255','B' => 'Zanzibar'),
  array('A' => '+263','B' => 'Zimbabwe')
);
